### PR TITLE
1.9 rework

### LINKED ISSUE #6: ArsMagica 2.0.4 really heavy framedrops
Hello,

if we place "Essence Refiner", "Inscription Table" or "Lectern", we lose 1/3-2/3 of our Frames. Can u look into it? If u need anymore information just tell me :)

Greetings

ps: if u need anything specific tested, we are 5 people willing to test the AM2 things on our server.

### PR DESCRIPTION
**Pull request by esotericist**
This, near as I can tell, actually fixes #6.

Adds getUpdateTag() implementations in the two places that probably need it (the crystal markers definitely do and I suspect it's a good idea to have in the AM Power class), and yanks the markAndNotifyBlock() calls in the most painful places. We probably don't want them anywhere, but I'm frankly kinda exhausted with chasing down the proper way to do this.

I still insist I am not a java programmer.

BTW, you probably want to revert the mimicstate stuff from a0673b2, since that breaks the rendering of the crafting altar when it's in a validated state. I actually spent a while trying to figure out what I broke with the crafting altar before I realized that it hasn't worked from 2.0.7 onward, and I just hadn't actually HAD a valid crafting altar since 2.0.6. :p 

Also, I got tired of doing chmod +x gradlew every time I synced. :D

### CODE REVIEW

**Comment by esotericist** [comment]
Or... maybe a0673b2 is okay? in my AM2-alone world, your 2.0.7 and 2.0.8 releases have a broken texture for the crafting altar, but in my survival world with like 150 mods, it works now? I don't understand :(

**Comment by esotericist** [comment]
... grr. crystal markers render in the right place, but their hitboxes are in the default 'up' position...

**Comment by esotericist** [comment]
Looks like my failure to include a getUpdateTag() in the inscription table causes it to sometimes crash the server.

There's probably others I missed; I forgot they didn't _all_ descend from AMPower, and so me having one there didn't help the inscription table.

Easy to fix. Still haven't figured out the hitbox problem for the crystal markers.

**Comment by EdwinMindcraft** [comment]
I'll merge this after my next commit

**Comment by EdwinMindcraft** [comment]
The crystal marker issue was an issue due to the fact that you removed the te-block sync code.

**Comment by esotericist** [comment]
If by 'te-block sync code' you mean markAndNotifyBlock() that HAS to go. It, itself, is THE cause of the FPS issue due to constant chunk update churning. I checked a bunch of other mods, and basically nobody uses it, and what little I could find in the minecraftforge forums indicated it's considered a bad idea. 

The stuff I added with getUpdateTag() is how it appears to be intended to implement TE synchronization in 1.9+

**Comment by esotericist** [comment]
as mentioned in one of my commit notes, williewillus put some more information here.
https://gist.github.com/williewillus/7945c4959b1142ece9828706b527c5a4

**Comment by EdwinMindcraft** [comment]
nah i meant the setBlockState part, just with an added check

**Comment by esotericist** [comment]
Ah, Okay. ... I didn't realize I removed that.

**Comment by EdwinMindcraft** [comment]
yay that's no problem, fixed it :p

**Comment by esotericist** [comment]
(still not a java programmer)

**Pull request closed without merging**
